# Generated by Django 5.0.14 on 2026-06-02 07:16

import apps.profiles.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(db_index=True, help_text='Custom URL handle at xpand.so/<handle>', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Handle must be 3-30 characters long and contain only lowercase letters, numbers, and underscores.', regex='^[a-z0-9_]{3,30}$'), apps.profiles.models.validate_reserved_handle])),
                ('display_name', models.CharField(max_length=60)),
                ('bio', models.TextField(blank=True, max_length=200)),
                ('is_visible', models.BooleanField(default=False)),
                ('verified_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('whatsapp-green', 'WhatsApp Green')], default='light', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
