# Generated by Django 5.0.14 on 2026-06-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
