# Generated by Django 5.0.14 on 2026-06-02 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('label', models.CharField(max_length=100)),
                ('surface_type', models.CharField(choices=[('group', 'Group'), ('community', 'Community'), ('channel', 'Channel'), ('chat', 'Chat'), ('business', 'Business'), ('other', 'Other')], default='other', max_length=20)),
                ('cta_text', models.CharField(blank=True, help_text='Custom CTA message on the action button', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='profiles.profile')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['profile', 'is_active', 'sort_order'], name='links_link_profile_38469e_idx')],
            },
        ),
    ]
