# Generated by Django 5.0.14 on 2026-06-09 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='links.link')),
            ],
            options={
                'indexes': [models.Index(fields=['link', 'phone_number'], name='links_linkc_link_id_3c4429_idx'), models.Index(fields=['link', 'ip_address'], name='links_linkc_link_id_9c98c7_idx')],
            },
        ),
    ]
