# Generated by Django 5.0.14 on 2026-06-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_linkclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkclick',
            name='visitor_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='linkclick',
            index=models.Index(fields=['link', 'visitor_id'], name='links_linkc_link_id_6b2943_idx'),
        ),
    ]
