# Generated by Django 5.0.14 on 2026-06-02 07:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url_snapshot', models.URLField(max_length=2048)),
                ('link_label_snapshot', models.CharField(max_length=100)),
                ('cta_text_snapshot', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="WhatsApp number must be in the format: '+919999999999'. Up to 15 digits allowed.", regex='^\\+?[1-9]\\d{1,14}$')])),
                ('message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='links.link')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['link', '-created_at'], name='leads_lead_link_id_63718d_idx')],
            },
        ),
    ]
