# Generated by Django 5.0.14 on 2026-06-08 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='links.link'),
        ),
    ]
